post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: string
                  format: base64
                  example: b'/9j/4RjQRXhpZgAASUkqAAgAAAAJADIBAgAUAAAAegAAABABAgAIAAAAjgAAACgBAwABAAAAAgAAABsBBQABAAAAlgAAABIBAwABAAA'
              required:
                - data
      responses:
        200:
          description: Echo response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
                    format: json
                    example:
                      ['Морозов', 'Иван', 'Денисович', 'Муж', '11.11.1234', 'Санкт-Петербург', '1234 567890']
