post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: string
                  format: base64
                  example: b'/9j/4RjQRXhpZgAASUkqAAgAAAAJADIBAgAUAAAAegAAABABAgAIAAAAjgAAACgBAwABAAAAAgAAABsBBQABAAAAlgAAABIBAwABAAA'
              required:
                - data
      responses:
        200:
          description: Echo response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
                    format: json
                    example: '{name: Иван, surname: Морозов, secondname: Денисович, gender: муж, bdate: 01.01.2345, city: Санкт-Петербург, series: 1234 567890}'
